spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barogo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: barogo
    password: barogo1234

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: false
        format_sql: true
        show_sql: true
    open-in-view: false

jwt:
  secretKey: "barogo-super-secret-key-barogo-super-secret-key"
  accessTokenExpiration: 600000 # 60 * 10 * 1000 = 10minutes