version: '3.8'

services:
  mysql:
    container_name: barogo-delivery-poc
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: barogo
      MYSQL_USER: barogo
      MYSQL_PASSWORD: barogo1234
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
